/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySkillsRouteImport } from './routes/company.skills'
import { Route as CompanyIntelligenceRouteImport } from './routes/company.intelligence'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySkillsRoute = CompanySkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyIntelligenceRoute = CompanyIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => CompanyRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/company/intelligence': typeof CompanyIntelligenceRoute
  '/company/skills': typeof CompanySkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/company/intelligence': typeof CompanyIntelligenceRoute
  '/company/skills': typeof CompanySkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/company/intelligence': typeof CompanyIntelligenceRoute
  '/company/skills': typeof CompanySkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/api/chat'
    | '/company/intelligence'
    | '/company/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/api/chat'
    | '/company/intelligence'
    | '/company/skills'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/api/chat'
    | '/company/intelligence'
    | '/company/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/skills': {
      id: '/company/skills'
      path: '/skills'
      fullPath: '/company/skills'
      preLoaderRoute: typeof CompanySkillsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/intelligence': {
      id: '/company/intelligence'
      path: '/intelligence'
      fullPath: '/company/intelligence'
      preLoaderRoute: typeof CompanyIntelligenceRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompanyRouteChildren {
  CompanyIntelligenceRoute: typeof CompanyIntelligenceRoute
  CompanySkillsRoute: typeof CompanySkillsRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyIntelligenceRoute: CompanyIntelligenceRoute,
  CompanySkillsRoute: CompanySkillsRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
